# run-healthsync-podman.ps1
# -----------------------------------------------------------------------------
# Run healthsync-activities.sh with real Google Drive credentials using Podman,
# then serve the rendered pages locally for browser inspection.
#
# Usage -first run (downloads from Drive):
#   powershell -ExecutionPolicy Bypass -File test\run-healthsync-podman.ps1 `
#       -Config .\config-healthsync.conf
#
# With Strava history migration (mounts your existing activities.ndjson):
#   powershell -ExecutionPolicy Bypass -File test\run-healthsync-podman.ps1 `
#       -Config .\config-healthsync.conf `
#       -StravaStore C:\path\to\strava-my-activities\activities.ndjson
#
# Re-render only (no Drive download, reuses a kept state dir):
#   powershell -ExecutionPolicy Bypass -File test\run-healthsync-podman.ps1 `
#       -Config .\config-healthsync.conf `
#       -StateDir C:\Temp\healthsync-run-20260714120000\state `
#       -SkipImport
#
# Parameters:
#   -Config <path>       Path to your healthsync.conf (required, never modified)
#   -Port <int>          Host port to serve on (default: 8088)
#   -StravaStore <path>  Path to an existing Strava activities.ndjson to import as
#                        history. Mounted at /import/activities.ndjson -matches the
#                        HEALTHSYNC_IMPORT_STRAVA_STORE="/import/activities.ndjson"
#                        line in config-healthsync.conf.
#   -StateDir <path>     Reuse an existing state dir from a previous -KeepOutput run.
#                        If omitted, a fresh temp dir is created.
#   -SkipImport          Skip the Drive download; just re-render HTML from the store.
#                        Requires -StateDir pointing at a populated state dir.
#   -KeepOutput          Keep the temp dirs when done so you can reuse with -StateDir.
#
# Requirements:
#   - Podman running on this machine
#   - Internet access (Google Drive OAuth + Open-Meteo for weather)
#   - A healthsync.conf with valid Google credentials and DRIVE_FOLDER_ID
# -----------------------------------------------------------------------------

param(
    [Parameter(Mandatory=$true)]
    [string]$Config,

    [int]$Port = 8088,

    [string]$StravaStore = '',

    [string]$StateDir = '',

    [switch]$SkipImport,

    [switch]$KeepOutput
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot  # test/ -> repo root

# ---- Validate inputs ---------------------------------------------------------

if (-not (Test-Path $Config)) {
    Write-Error "Config file not found: $Config"
    exit 1
}
$ConfigAbsolute = (Resolve-Path $Config).Path

if ($SkipImport -and -not $StateDir) {
    Write-Error "-SkipImport requires -StateDir pointing at a populated state directory."
    exit 1
}

if ($StateDir -and -not (Test-Path $StateDir)) {
    Write-Error "StateDir not found: $StateDir"
    exit 1
}

$StravaStoreAbsolute = ''
if ($StravaStore) {
    if (-not (Test-Path $StravaStore)) {
        Write-Error "StravaStore not found: $StravaStore"
        exit 1
    }
    $StravaStoreAbsolute = (Resolve-Path $StravaStore).Path
}

# ---- Prepare directories -----------------------------------------------------

$TempRoot = Join-Path $env:TEMP "healthsync-run-$(Get-Date -Format 'yyyyMMddHHmmss')"
$WebDir   = Join-Path $TempRoot 'web'

if ($StateDir) {
    $UseStateDir = (Resolve-Path $StateDir).Path
    Write-Host "==> Reusing state dir: $UseStateDir"
} else {
    $UseStateDir = Join-Path $TempRoot 'state'
    New-Item -ItemType Directory -Force $UseStateDir | Out-Null
}

New-Item -ItemType Directory -Force "$WebDir\strava\me\details" | Out-Null
New-Item -ItemType Directory -Force "$WebDir\strava\me\gpx"     | Out-Null
New-Item -ItemType Directory -Force "$WebDir\cgi-bin"           | Out-Null

# ---- Generate a wrapper config -----------------------------------------------
# Sources the user's credentials-only config, then forces container-local paths.
# Any HEALTHSYNC_STATE_DIR / WEB_DIR lines in the user's config are overridden
# because our assignments come after the dot-source.

$WrapperConfig = Join-Path $TempRoot 'container.conf'
[System.IO.File]::WriteAllText($WrapperConfig, @"
# Auto-generated by run-healthsync-podman.ps1 -do not edit.
# Sources real credentials, then overrides all path variables for the container.
. /credentials.conf
HEALTHSYNC_STATE_DIR="/state"
HEALTHSYNC_WEB_DIR="/www/strava/me"
HEALTHSYNC_BIKE_DATA="/state/bike-service.json"
HEALTHSYNC_BIKE_ASSIGN="/state/bike-assignments.json"
HEALTHSYNC_CGI_DIR="/www/cgi-bin"
"@)

# Container names
$RunName   = 'healthsync-live-run'
$ServeName = 'healthsync-live-serve'

function Stop-Containers {
    & podman rm -f $RunName   2>$null | Out-Null
    & podman rm -f $ServeName 2>$null | Out-Null
}

Stop-Containers

# ---- Helper: extract a KEY="value" line from a POSIX shell config file ------

function Get-ShellConfigValue {
    param([string]$FilePath, [string]$Key)
    $raw = [System.IO.File]::ReadAllText($FilePath)
    if ($raw -match "(?m)^$Key=`"([^`"]+)`"") { return $Matches[1] }
    if ($raw -match "(?m)^$Key='([^']+)'")    { return $Matches[1] }
    if ($raw -match "(?m)^$Key=(\S+)")         { return $Matches[1] }
    return $null
}

# ---- Google OAuth device-flow re-authorization ------------------------------
# Reads CLIENT_ID/SECRET from the user's config, runs the device authorization
# flow via PowerShell Invoke-RestMethod (no extra tools needed), then writes
# the new GOOGLE_REFRESH_TOKEN back into the config file in-place.

function Invoke-GoogleDeviceAuth {
    $clientId     = Get-ShellConfigValue $ConfigAbsolute 'GOOGLE_CLIENT_ID'
    $clientSecret = Get-ShellConfigValue $ConfigAbsolute 'GOOGLE_CLIENT_SECRET'

    if (-not $clientId -or -not $clientSecret) {
        Write-Host "Cannot read GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET from $ConfigAbsolute" -ForegroundColor Red
        return $false
    }

    # Google no longer supports the device flow for Desktop app OAuth clients.
    # Use the loopback redirect flow instead: start a local HTTP listener, open
    # the browser, capture the auth code from the redirect, exchange for tokens.
    $port        = 9876
    $redirectUri = "http://localhost:$port/"
    $state       = [System.Guid]::NewGuid().ToString('N').Substring(0, 16)

    $authUrl = 'https://accounts.google.com/o/oauth2/v2/auth' +
               "?client_id=$([uri]::EscapeDataString($clientId))" +
               "&redirect_uri=$([uri]::EscapeDataString($redirectUri))" +
               "&response_type=code" +
               "&scope=$([uri]::EscapeDataString('https://www.googleapis.com/auth/drive.readonly'))" +
               "&access_type=offline" +
               "&prompt=consent" +
               "&state=$state"

    $listener = [System.Net.HttpListener]::new()
    $listener.Prefixes.Add("http://localhost:$port/")
    try {
        $listener.Start()
    } catch {
        Write-Host "Cannot bind to http://localhost:$port/ - $_" -ForegroundColor Red
        return $false
    }

    Write-Host ""
    Write-Host "==> Opening browser for Google Drive authorization ..." -ForegroundColor Yellow
    Write-Host "    Listening on http://localhost:$port/ for the OAuth callback."
    Write-Host ""
    Start-Process $authUrl

    Write-Host "Waiting for you to authorize in the browser ..."

    $code = $null
    try {
        $contextTask = $listener.GetContextAsync()
        $gotIt = $contextTask.Wait([System.TimeSpan]::FromMinutes(5))

        if (-not $gotIt) {
            Write-Host "Timed out waiting for browser callback." -ForegroundColor Red
            return $false
        }

        $ctx   = $contextTask.Result
        $query = $ctx.Request.Url.Query   # ?code=xxx&state=yyy  (or ?error=access_denied)

        # Return a simple page so the browser doesn't show a connection error
        $html  = '<html><body style="font-family:sans-serif;padding:2em"><h2>Authorization complete.</h2><p>You can close this tab.</p></body></html>'
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($html)
        $ctx.Response.ContentType     = 'text/html; charset=utf-8'
        $ctx.Response.ContentLength64 = $bytes.Length
        $ctx.Response.OutputStream.Write($bytes, 0, $bytes.Length)
        $ctx.Response.OutputStream.Close()

        if ($query -match '[?&]error=([^&]+)') {
            Write-Host "Authorization denied by user: $([uri]::UnescapeDataString($Matches[1]))" -ForegroundColor Red
            return $false
        }
        if ($query -notmatch '[?&]code=([^&]+)') {
            Write-Host "No auth code in callback. Raw query: $query" -ForegroundColor Red
            return $false
        }
        $code = [uri]::UnescapeDataString($Matches[1])

    } finally {
        $listener.Stop()
    }

    # Exchange the auth code for tokens
    Write-Host ""
    Write-Host "==> Exchanging auth code for tokens ..." -ForegroundColor Cyan
    $tokRaw = & curl.exe -s `
        --data-urlencode "client_id=$clientId" `
        --data-urlencode "client_secret=$clientSecret" `
        --data-urlencode "code=$code" `
        --data-urlencode "redirect_uri=$redirectUri" `
        -d 'grant_type=authorization_code' `
        'https://oauth2.googleapis.com/token'

    if (-not $tokRaw) {
        Write-Host "No response from token endpoint." -ForegroundColor Red
        return $false
    }
    $tok = $tokRaw | ConvertFrom-Json
    if ($tok.error) {
        Write-Host "Token exchange failed: $($tok.error) - $($tok.error_description)" -ForegroundColor Red
        return $false
    }
    if (-not $tok.refresh_token) {
        Write-Host "No refresh_token returned. Revoke app access at myaccount.google.com/permissions and retry." -ForegroundColor Yellow
        return $false
    }

    # Write the new refresh token back into the user's config file in-place
    $raw     = [System.IO.File]::ReadAllText($ConfigAbsolute)
    $updated = $raw -replace '(?m)^GOOGLE_REFRESH_TOKEN=.*$', "GOOGLE_REFRESH_TOKEN=`"$($tok.refresh_token)`""
    if ($updated -eq $raw) {
        $updated = $raw.TrimEnd() + "`nGOOGLE_REFRESH_TOKEN=`"$($tok.refresh_token)`"`n"
    }
    # Write without BOM — POSIX sh chokes on the UTF-8 BOM preamble when sourcing
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($ConfigAbsolute, $updated, $utf8NoBom)
    Write-Host "==> GOOGLE_REFRESH_TOKEN updated in $ConfigAbsolute" -ForegroundColor Green
    return $true
}

try {
    # ---- 1. Run healthsync-activities.sh -------------------------------------
    $importFlag = if ($SkipImport) { '0' } else { '1' }
    $modeLabel  = if ($SkipImport) { 're-render only (HEALTHSYNC_IMPORT_ENABLED=0)' } `
                                   else { 'full Drive download' }
    Write-Host ""
    Write-Host "==> Running healthsync-activities.sh ($modeLabel) ..."
    Write-Host "    State : $UseStateDir"
    Write-Host "    Web   : $WebDir"
    Write-Host ""

    # Build the volume list; add Strava store mount only when -StravaStore was given.
    # The config has HEALTHSYNC_IMPORT_STRAVA_STORE="/import/activities.ndjson" —
    # mount the file at exactly that path so the script picks it up automatically.
    $volArgs = @(
        '-v', "${RepoRoot}:/app:ro",
        '-v', "${ConfigAbsolute}:/credentials.conf:ro",
        '-v', "${WrapperConfig}:/etc/healthsync-activities.conf:ro",
        '-v', "${UseStateDir}:/state",
        '-v', "${WebDir}:/www"
    )
    if ($StravaStoreAbsolute) {
        $volArgs += '-v', "${StravaStoreAbsolute}:/import/activities.ndjson:ro"
        Write-Host "    Strava import: $StravaStoreAbsolute"
    }

    & podman run --rm --name $RunName @volArgs `
        -e "HEALTHSYNC_IMPORT_ENABLED=$importFlag" `
        alpine:3.20 `
        sh -c 'apk add --no-cache curl jq ca-certificates >/dev/null 2>&1 && sh /app/healthsync-activities.sh'

    if ($LASTEXITCODE -ne 0) {
        # Detect whether it was a Drive token failure via drive-status.json
        $isTokenError = $false
        $dsPath = Join-Path $WebDir 'strava\me\drive-status.json'
        if (Test-Path $dsPath) {
            if ((Get-Content $dsPath -Raw) -match '"ok"\s*:\s*false') { $isTokenError = $true }
        }

        if ($isTokenError) {
            Write-Host ""
            Write-Host "Drive token expired - starting re-authorization flow ..." -ForegroundColor Yellow
            $reAuthed = Invoke-GoogleDeviceAuth
            if (-not $reAuthed) { exit 1 }

            Write-Host ""
            Write-Host "==> Re-running healthsync-activities.sh with refreshed token ..." -ForegroundColor Cyan
            Write-Host ""
            & podman run --rm --name $RunName @volArgs `
                -e "HEALTHSYNC_IMPORT_ENABLED=$importFlag" `
                alpine:3.20 `
                sh -c 'apk add --no-cache curl jq ca-certificates >/dev/null 2>&1 && sh /app/healthsync-activities.sh'

            if ($LASTEXITCODE -ne 0) {
                Write-Host ""
                Write-Host "healthsync-activities.sh still failed after re-authorization - check output above." -ForegroundColor Red
                exit 1
            }
        } else {
            Write-Host ""
            Write-Host "healthsync-activities.sh failed - check output above." -ForegroundColor Red
            Write-Host ""
            Write-Host "Common causes:"
            Write-Host "  - Wrong DRIVE_FOLDER_ID in $Config"
            Write-Host "  - No activities in the Drive folder yet"
            exit 1
        }
    }

    # ---- 2. Show what was generated ------------------------------------------
    $activitiesJson = Join-Path $WebDir 'strava\me\activities.json'
    if (Test-Path $activitiesJson) {
        try {
            $data = Get-Content $activitiesJson -Raw | ConvertFrom-Json
            $count = $data.activities.Count
            $gen   = $data.generatedAt
            Write-Host ""
            Write-Host "==> activities.json: $count activities, generated $gen" -ForegroundColor Cyan
        } catch {}
    }

    $driveStatus = Join-Path $WebDir 'strava\me\drive-status.json'
    if (Test-Path $driveStatus) {
        $ds = Get-Content $driveStatus -Raw
        if ($ds -match '"ok":true') {
            Write-Host "==> drive-status.json: ok" -ForegroundColor Green
        } else {
            Write-Host "==> drive-status.json: $ds" -ForegroundColor Yellow
        }
    }

    # ---- 3. Serve with busybox httpd ------------------------------------------
    Write-Host ""
    Write-Host "==> Starting server on port $Port ..."

    & podman run -d --name $ServeName `
        -p "${Port}:8080" `
        -v "${WebDir}:/www:ro" `
        alpine:3.20 `
        sh -c 'apk add --no-cache busybox-extras >/dev/null 2>&1 && httpd -f -p 8080 -h /www'

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to start serve container." -ForegroundColor Red
        exit 1
    }

    # Wait for httpd to become ready
    $ready = $false
    for ($i = 0; $i -lt 15; $i++) {
        Start-Sleep -Seconds 1
        try {
            $null = Invoke-WebRequest -Uri "http://localhost:$Port/strava/me/index.html" `
                                      -UseBasicParsing -TimeoutSec 2
            $ready = $true
            break
        } catch {}
    }

    if (-not $ready) {
        Write-Host "Server did not respond after 15 s -try opening manually." -ForegroundColor Yellow
    }

    Write-Host ""
    Write-Host "==> Pages are live at:" -ForegroundColor Green
    Write-Host "    My Activities : http://localhost:$Port/strava/me/"
    Write-Host "    Stats         : http://localhost:$Port/strava/me/stats.html"
    Write-Host "    Bike service  : http://localhost:$Port/strava/me/bike.html"
    Write-Host "    Drive status  : http://localhost:$Port/strava/me/drive-status.json"
    Write-Host ""
    if ($KeepOutput) {
        Write-Host "    State dir (kept): $UseStateDir"
        Write-Host "    Web dir   (kept): $WebDir"
        Write-Host ""
        Write-Host "    Re-render next time with:"
        Write-Host "      -StateDir `"$UseStateDir`" -SkipImport"
        Write-Host ""
    }

    Start-Process "http://localhost:$Port/strava/me/"
    Read-Host "Press Enter to stop"

} finally {
    Write-Host ""
    Write-Host "==> Stopping containers ..."
    Stop-Containers

    if ($KeepOutput) {
        Write-Host "Output kept:"
        Write-Host "  State : $UseStateDir"
        Write-Host "  Web   : $WebDir"
    } else {
        Remove-Item -Recurse -Force $TempRoot -ErrorAction SilentlyContinue
        Write-Host "Temp output removed."
    }
}
