# run-scrape-test.ps1
# -----------------------------------------------------------------------------
# Test strava-my-activities.sh in STRAVA_MY_SOURCE=scrape mode.
# Makes real HTTP requests to strava.com using a browser session cookie.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File test\run-scrape-test.ps1 `
#       -SessionCookie "paste_strava4_session_value_here"
#
# The first run fetches MaxPages*20 activities plus DetailMax detail pages.
# Keep MaxPages small (2-3) initially to verify the parsing works before
# pulling your full history.
#
# Re-render only (reuse a previous -KeepOutput state dir):
#   powershell -ExecutionPolicy Bypass -File test\run-scrape-test.ps1 `
#       -SessionCookie "..." -StateDir C:\Temp\scrape-test-...\state -SkipImport
#
# Parameters:
#   -SessionCookie <string>   Value of _strava4_session cookie (required)
#                             DevTools: F12 -> Application -> Cookies -> strava.com
#   -Port <int>               Host port for the preview server (default: 8091)
#   -MaxPages <int>           Pages to fetch; 20 activities/page (default: 2)
#   -DetailMax <int>          Detail pages to fetch this run; 0 to skip (default: 3)
#   -StateDir <path>          Reuse an existing state dir from a -KeepOutput run
#   -SkipImport               Skip the Strava fetch; only re-render HTML
#   -KeepOutput               Keep temp dirs after exit (shows paths for reuse)
#   -NoBrowser                Do not open a browser window automatically
#
# Requirements:
#   - Podman (podman.exe on PATH)
#   - Internet access to strava.com
# -----------------------------------------------------------------------------

param(
    [Parameter(Mandatory=$true)]
    [string]$SessionCookie,

    [int]$Port = 8091,

    [int]$MaxPages = 2,

    [int]$DetailMax = 3,

    [string]$StateDir = '',

    [switch]$SkipImport,

    [switch]$KeepOutput,

    [switch]$NoBrowser
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot   # test/ -> repo root

# ---- Validate inputs ---------------------------------------------------------

if ($SkipImport -and -not $StateDir) {
    Write-Error "-SkipImport requires -StateDir pointing at a populated state directory."
    exit 1
}
if ($StateDir -and -not (Test-Path $StateDir)) {
    Write-Error "StateDir not found: $StateDir"
    exit 1
}

# ---- Prepare temp directories ------------------------------------------------

$TempRoot = Join-Path $env:TEMP "scrape-test-$(Get-Date -Format 'yyyyMMddHHmmss')"
$WebDir   = Join-Path $TempRoot 'web'

if ($StateDir) {
    $UseStateDir = (Resolve-Path $StateDir).Path
    Write-Host ""
    Write-Host "==> Reusing state dir: $UseStateDir"
} else {
    $UseStateDir = Join-Path $TempRoot 'state'
    New-Item -ItemType Directory -Force $UseStateDir | Out-Null
}

New-Item -ItemType Directory -Force "$WebDir\strava\me\details" | Out-Null
New-Item -ItemType Directory -Force "$WebDir\strava\me\gpx"     | Out-Null
New-Item -ItemType Directory -Force "$WebDir\cgi-bin"           | Out-Null

# ---- Generate config file (no API credentials needed in scrape mode) ---------

$ConfigFile = Join-Path $TempRoot 'strava-my-activities.conf'
# NOTE: SessionCookie is written into the config file (chmod 600 by the script).
# It is NOT logged to stdout below.
[System.IO.File]::WriteAllText($ConfigFile, @"
# Auto-generated by run-scrape-test.ps1
STRAVA_MY_SOURCE="scrape"
STRAVA_SESSION_COOKIE="$SessionCookie"
STRAVA_MY_WEB_DIR="/www/strava/me"
STRAVA_MY_STATE_DIR="/state"
STRAVA_MY_DETAIL_DIR="/www/strava/me/details"
STRAVA_MY_BIKE_DATA="/state/bike-service.json"
STRAVA_MY_BIKE_ASSIGN="/state/bike-assignments.json"
STRAVA_MY_CGI_DIR="/www/cgi-bin"
STRAVA_MY_MAX_PAGES="$MaxPages"
STRAVA_MY_PER_PAGE="200"
STRAVA_MY_DETAIL_MAX_PER_RUN="$DetailMax"
STRAVA_MY_DETAIL_SLEEP="1"
STRAVA_MY_PRUNE_DELETED="1"
"@)

$RunName   = 'strava-scrape-run'
$ServeName = 'strava-scrape-serve'

function Stop-Containers {
    & podman rm -f $RunName   2>$null | Out-Null
    & podman rm -f $ServeName 2>$null | Out-Null
}

# Kill any container already bound to the target port.
& podman ps --format "{{.Names}}\t{{.Ports}}" 2>$null |
    Where-Object { $_ -match ":$Port->" } |
    ForEach-Object { & podman stop ($_ -split "\t")[0] 2>$null | Out-Null }

Stop-Containers

try {
    # ---- 1. Run strava-my-activities.sh ----------------------------------------

    $importFlag = if ($SkipImport) { '0' } else { '1' }
    if ($SkipImport) {
        $modeLabel = 're-render only (STRAVA_MY_IMPORT_ENABLED=0)'
    } else {
        $modeLabel = "scrape mode -- fetching $MaxPages page(s) x 20 from strava.com"
    }

    Write-Host ""
    Write-Host "==> Running strava-my-activities.sh ($modeLabel)" -ForegroundColor Cyan
    Write-Host "    State dir : $UseStateDir"
    Write-Host "    Web dir   : $WebDir"
    Write-Host "    DetailMax : $DetailMax"
    Write-Host ""
    Write-Host "NOTE: This makes real HTTP requests to strava.com." -ForegroundColor Yellow
    Write-Host ""

    $volArgs = @(
        '-v', "${RepoRoot}:/app:ro",
        '-v', "${ConfigFile}:/etc/strava-my-activities.conf:ro",
        '-v', "${UseStateDir}:/state",
        '-v', "${WebDir}:/www"
    )

    & podman run --rm --name $RunName @volArgs `
        -e "STRAVA_MY_IMPORT_ENABLED=$importFlag" `
        alpine:3.20 `
        sh -c 'apk add --no-cache curl jq ca-certificates >/dev/null 2>&1 && sh /app/strava-my-activities.sh'

    if ($LASTEXITCODE -ne 0) {
        Write-Host ""
        Write-Host "strava-my-activities.sh failed - check output above." -ForegroundColor Red
        Write-Host ""
        Write-Host "Common causes in scrape mode:" -ForegroundColor Yellow
        Write-Host "  - STRAVA_SESSION_COOKIE has expired (copy a fresh _strava4_session value)"
        Write-Host "  - Network error inside the container (check Podman DNS/proxy settings)"
        exit 1
    }

    # ---- 2. Summarise results ---------------------------------------------------

    $activitiesJson = Join-Path $WebDir 'strava\me\activities.json'
    if (Test-Path $activitiesJson) {
        try {
            $data  = Get-Content $activitiesJson -Raw | ConvertFrom-Json
            $count = $data.activities.Count
            $gen   = $data.generatedAt
            Write-Host ""
            Write-Host "==> activities.json: $count activities, generated $gen" -ForegroundColor Cyan
        } catch {
            Write-Host "==> activities.json written but could not parse it." -ForegroundColor Yellow
        }
    } else {
        Write-Host "==> activities.json not found - import likely failed." -ForegroundColor Yellow
    }

    $storeFile = Join-Path $UseStateDir 'activities.ndjson'
    if (Test-Path $storeFile) {
        $storeCount = @(Get-Content $storeFile).Count
        Write-Host "==> Store: $storeCount total records" -ForegroundColor Cyan
    }

    $detailDir = Join-Path $WebDir 'strava\me\details'
    if (Test-Path $detailDir) {
        $detailCount = @(Get-ChildItem $detailDir -Filter '*.json' -ErrorAction SilentlyContinue).Count
        Write-Host "==> Detail files: $detailCount" -ForegroundColor Cyan
        if ($DetailMax -gt 0 -and $detailCount -eq 0) {
            Write-Host ""
            Write-Host "WARN: $DetailMax detail page(s) were requested but 0 saved." -ForegroundColor Yellow
            Write-Host "  The HTML extraction patterns may need tuning for the current Strava page format."
            Write-Host "  Check the log above for 'could not extract JSON from page' messages."
            Write-Host "  See: strava-my-activities.sh section 3b (_sc extraction patterns)"
        }
    }

    # ---- 3. Start lighttpd serve container -------------------------------------

    Write-Host ""
    Write-Host "==> Starting preview server on port $Port ..." -ForegroundColor Cyan

    $ConfFile = Join-Path $TempRoot 'lighttpd.conf'
    [System.IO.File]::WriteAllLines($ConfFile, [string[]]@(
        'server.port          = 8080',
        'server.document-root = "/www"',
        'server.bind          = "0.0.0.0"',
        'server.modules       = ("mod_cgi","mod_indexfile","mod_staticfile","mod_dirlisting")',
        'server.errorlog      = "/dev/stderr"',
        'index-file.names     = ("index.html")',
        '$HTTP["url"] =~ "^/cgi-bin/" {',
        '  cgi.assign = ("" => "/bin/sh")',
        '}'
    ))

    & podman run -d --name $ServeName `
        -p "${Port}:8080" `
        -v "${WebDir}:/www:ro" `
        -v "${UseStateDir}:/state:ro" `
        -v "${ConfFile}:/tmp/lighttpd.conf:ro" `
        alpine:3.20 `
        sh -c 'apk add --no-cache lighttpd >/dev/null 2>&1 && lighttpd -D -f /tmp/lighttpd.conf'

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to start serve container." -ForegroundColor Red
        exit 1
    }

    # Wait up to 15 s for lighttpd to come up
    $ready = $false
    for ($i = 0; $i -lt 15; $i++) {
        Start-Sleep -Seconds 1
        try {
            $null = Invoke-WebRequest -Uri "http://localhost:$Port/" -UseBasicParsing -TimeoutSec 2
            $ready = $true
            break
        } catch {}
    }
    if ($ready) {
        Write-Host "    Server ready." -ForegroundColor Green
    } else {
        Write-Host "    WARN: server did not respond in 15 s - check: podman logs $ServeName" -ForegroundColor Yellow
    }

    # ---- 4. Print URLs ---------------------------------------------------------

    $baseUrl = "http://localhost:$Port/strava/me"
    Write-Host ""
    Write-Host "==> Pages:" -ForegroundColor Green
    Write-Host "    Dashboard    : $baseUrl/"
    Write-Host "    Stats        : $baseUrl/stats.html"
    Write-Host "    Bike service : $baseUrl/bike.html"
    Write-Host "    activities.json raw : $baseUrl/activities.json"

    if ((Test-Path $storeFile) -and (Test-Path $detailDir)) {
        $detailFiles = @(Get-ChildItem $detailDir -Filter '*.json' -ErrorAction SilentlyContinue)
        if ($detailFiles.Count -gt 0) {
            Write-Host ""
            Write-Host "    Activity detail pages (first $([Math]::Min(3,$detailFiles.Count))):"
            $detailFiles | Select-Object -First 3 | ForEach-Object {
                $id = $_.BaseName
                Write-Host "      $baseUrl/activity.html?id=$id"
            }
        }
    }

    Write-Host ""
    if ($KeepOutput) {
        Write-Host "==> Output kept (-KeepOutput):" -ForegroundColor Cyan
        Write-Host "    State dir : $UseStateDir"
        Write-Host "    Web dir   : $WebDir"
        Write-Host ""
        Write-Host "    Re-render next time with:"
        Write-Host "      -SessionCookie `"...`" -StateDir `"$UseStateDir`" -SkipImport"
        Write-Host ""
    }

    if (-not $NoBrowser) {
        try { Start-Process "$baseUrl/" } catch {}
    }

    Read-Host "Press Enter to stop"

} finally {
    Write-Host ""
    Write-Host "==> Stopping containers ..."
    Stop-Containers

    if ($KeepOutput) {
        Write-Host "Output kept:"
        Write-Host "  State : $UseStateDir"
        Write-Host "  Web   : $WebDir"
    } else {
        Remove-Item -Recurse -Force $TempRoot -ErrorAction SilentlyContinue
        Write-Host "Temp output removed."
    }
}
