server.document-root = "/www"
server.port          = 80
server.bind          = "0.0.0.0"
server.modules       = ("mod_cgi", "mod_indexfile", "mod_staticfile", "mod_dirlisting")
server.errorlog      = "/dev/stderr"
server.pid-file      = "/tmp/lighttpd.pid"
index-file.names     = ("index.html")
$HTTP["url"] =~ "^/cgi-bin/" {
  cgi.assign = ("" => "/bin/sh")
}
